### ISSUE TITLE
Build失败

### ISSUE THREAD

**Issue by kjlawrencelaw** [daihy8759/ieaseMusic#3]
RAW

> imac:ieasemusic lawrencelaw$ yarn install
> yarn install v1.22.4
> [1/4] 🔍  Resolving packages...
> success Already up-to-date.
> ✨  Done in 1.01s.

> imac:ieasemusic lawrencelaw$ yarn build
> yarn run v1.22.4
> $ npm run clean && npm run build-all && electron-builder
> npm WARN lifecycle The node binary used for scripts is /var/folders/8f/7vs415913qv8dy0845_kbj2c0000gp/T/yarn--1590326002034-0.7223147133295764/node but npm is using /usr/local/Cellar/node/14.3.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
> 
> > ieaseMusic@1.0.0 clean /Users/lawrencelaw/ieaseMusic
> > rimraf dist && rimraf build
> 
> npm WARN lifecycle The node binary used for scripts is /var/folders/8f/7vs415913qv8dy0845_kbj2c0000gp/T/yarn--1590326002034-0.7223147133295764/node but npm is using /usr/local/Cellar/node/14.3.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
> 
> > ieaseMusic@1.0.0 build-all /Users/lawrencelaw/ieaseMusic
> > npm run build-main && npm run build-renderer
> 
> npm WARN lifecycle The node binary used for scripts is /var/folders/8f/7vs415913qv8dy0845_kbj2c0000gp/T/yarn--1590326002034-0.7223147133295764/node but npm is using /usr/local/Cellar/node/14.3.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
> 
> > ieaseMusic@1.0.0 build-main /Users/lawrencelaw/ieaseMusic
> > webpack --config webpack/webpack.main.prod.config.js
> 
> Hash: a377ebe8e4acf1199256
> Version: webpack 4.43.0
> Time: 1590ms
> Built at: 05/24/2020 9:13:26 PM
>   Asset     Size  Chunks             Chunk Names
> main.js  623 KiB       0  [emitted]  main
> Entrypoint main = main.js
>  [0] external "electron" 42 bytes {0} [built]
>  [1] external "path" 42 bytes {0} [built]
>  [2] external "fs" 42 bytes {0} [built]
>  [3] external "util" 42 bytes {0} [built]
>  [4] external "assert" 42 bytes {0} [built]
>  [6] (webpack)/buildin/harmony-module.js 573 bytes {0} [built]
>  [8] external "events" 42 bytes {0} [built]
> [21] external "os" 42 bytes {0} [built]
> [33] external "url" 42 bytes {0} [built]
> [34] ./src/main/ipcMainSets.ts 3.17 KiB {0} [built]
> [36] ./src/shared/storage.ts 988 bytes {0} [built]
> [38] ./src/main/index.ts 7.84 KiB {0} [built]
> [51] external "child_process" 42 bytes {0} [built]
> [54] external "https" 42 bytes {0} [built]
> [69] external "tty" 42 bytes {0} [built]
>     + 112 hidden modules
> npm WARN lifecycle The node binary used for scripts is /var/folders/8f/7vs415913qv8dy0845_kbj2c0000gp/T/yarn--1590326002034-0.7223147133295764/node but npm is using /usr/local/Cellar/node/14.3.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
> 
> > ieaseMusic@1.0.0 build-renderer /Users/lawrencelaw/ieaseMusic
> > webpack --config webpack/webpack.renderer.prod.config.js
> 
> Warning: React version not specified in eslint-plugin-react settings. See https://github.com/yannickcr/eslint-plugin-react#configuration .
> Hash: b31e37e9dd269c997a33
> Version: webpack 4.43.0
> Time: 23817ms
> Built at: 05/24/2020 9:13:51 PM
>  19 assets
> Entrypoint app = vendor.8c7951b8dae59faa8e86.chunk.js app.f41d85dbeebac4bac34b.js
>   [3] (webpack)/buildin/harmony-module.js 573 bytes {0} [built]
>   [8] ./node_modules/@material-ui/core/esm/styles/withStyles.js + 1 modules 4.71 KiB {0} [built]
>       |    2 modules
>  [10] external "electron" 42 bytes {2} [built]
>  [11] ./src/renderer/stores/controller.ts 11.6 KiB {2} [built]
>  [12] ./src/renderer/context.tsx 1.65 KiB {2} [built]
>  [15] ./node_modules/react-router/esm/react-router.js + 1 modules 29.9 KiB {0} [built]
>       |    2 modules
>  [41] ./node_modules/history/esm/history.js + 2 modules 30.6 KiB {0} [built]
>       |    3 modules
>  [47] ./src/renderer/utils/lastfm.ts 4.97 KiB {2} [built]
>  [49] ./src/renderer/stores/upnext.ts 3.84 KiB {2} [built]
>  [77] ./src/renderer/stores/preferences.ts 21.1 KiB {2} [built]
> [192] ./src/renderer/App.tsx 7.43 KiB {2} [built]
> [202] ./src/renderer/stores/index.ts 1.51 KiB {2} [built]
> [235] ./src/renderer/routes/index.tsx 5.42 KiB {2} [built]
> [273] ./src/renderer/index.tsx 426 bytes {2} [built]
> [351] ./src/renderer/App.less 587 bytes {2} [built]
>     + 622 hidden modules
> 
> WARNING in ./src/renderer/components/Header/index.tsx
> Module Warning (from ./node_modules/eslint-loader/index.js):
> 
> /Users/lawrencelaw/ieaseMusic/src/renderer/components/Header/index.tsx
>   18:31  warning  'playing' is assigned a value but never used  @typescript-eslint/no-unused-vars
> 
> ✖ 1 problem (0 errors, 1 warning)
> 
>  @ ./src/renderer/views/FM/index.tsx 24:0-39 130:38-44
>  @ ./src/renderer/routes/index.tsx
>  @ ./src/renderer/App.tsx
>  @ ./src/renderer/index.tsx
> 
> WARNING in ./src/renderer/views/FM/index.tsx
> Module Warning (from ./node_modules/eslint-loader/index.js):
> 
> /Users/lawrencelaw/ieaseMusic/src/renderer/views/FM/index.tsx
>   172:42  warning  '_' is defined but never used  @typescript-eslint/no-unused-vars
> 
> ✖ 1 problem (0 errors, 1 warning)
> 
>  @ ./src/renderer/routes/index.tsx 30:28-49
>  @ ./src/renderer/App.tsx
>  @ ./src/renderer/index.tsx
> 
> ERROR in ./src/renderer/views/Search/index.tsx
> Module Error (from ./node_modules/eslint-loader/index.js):
> 
> /Users/lawrencelaw/ieaseMusic/src/renderer/views/Search/index.tsx
>   70:25  error  Unexpected empty arrow function  @typescript-eslint/no-empty-function
> 
> ✖ 1 problem (1 error, 0 warnings)
> 
>  @ ./src/renderer/routes/index.tsx 29:32-57
>  @ ./src/renderer/App.tsx
>  @ ./src/renderer/index.tsx
> Child html-webpack-plugin for "index.html":
>      1 asset
>     Entrypoint undefined = index.html
>     [0] ./node_modules/html-webpack-plugin/lib/loader.js!./src/renderer/index.html 380 bytes {0} [built]
>     [2] (webpack)/buildin/module.js 497 bytes {0} [built]
>         + 1 hidden module
> npm ERR! code ELIFECYCLE
> npm ERR! errno 2
> npm ERR! ieaseMusic@1.0.0 build-renderer: `webpack --config webpack/webpack.renderer.prod.config.js`
> npm ERR! Exit status 2
> npm ERR! 
> npm ERR! Failed at the ieaseMusic@1.0.0 build-renderer script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/lawrencelaw/.npm/_logs/2020-05-24T13_13_51_981Z-debug.log
> npm ERR! code ELIFECYCLE
> npm ERR! errno 2
> npm ERR! ieaseMusic@1.0.0 build-all: `npm run build-main && npm run build-renderer`
> npm ERR! Exit status 2
> npm ERR! 
> npm ERR! Failed at the ieaseMusic@1.0.0 build-all script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/lawrencelaw/.npm/_logs/2020-05-24T13_13_52_069Z-debug.log
> error Command failed with exit code 2.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

以下是log

> 0 info it worked if it ends with ok
> 1 verbose cli [
> 1 verbose cli   '/usr/local/Cellar/node/14.3.0/bin/node',
> 1 verbose cli   '/usr/local/bin/npm',
> 1 verbose cli   'run',
> 1 verbose cli   'build-all'
> 1 verbose cli ]
> 2 info using npm@6.14.4
> 3 info using node@v14.3.0
> 4 verbose run-script [ 'prebuild-all', 'build-all', 'postbuild-all' ]
> 5 info lifecycle ieaseMusic@1.0.0~prebuild-all: ieaseMusic@1.0.0
> 6 info lifecycle ieaseMusic@1.0.0~build-all: ieaseMusic@1.0.0
> 7 warn lifecycle The node binary used for scripts is /var/folders/8f/7vs415913qv8dy0845_kbj2c0000gp/T/yarn--1590326002034-0.7223147133295764/node but npm is using /usr/local/Cellar/node/14.3.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
> 8 verbose lifecycle ieaseMusic@1.0.0~build-all: unsafe-perm in lifecycle true
> 9 verbose lifecycle ieaseMusic@1.0.0~build-all: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/lawrencelaw/ieaseMusic/node_modules/.bin:/var/folders/8f/7vs415913qv8dy0845_kbj2c0000gp/T/yarn--1590326002034-0.7223147133295764:/Users/lawrencelaw/ieaseMusic/node_modules/.bin:/Users/lawrencelaw/.config/yarn/link/node_modules/.bin:/usr/local/Cellar/node/14.3.0/libexec/lib/node_modules/npm/bin/node-gyp-bin:/usr/local/Cellar/node/14.3.0/lib/node_modules/npm/bin/node-gyp-bin:/usr/local/Cellar/node/14.3.0/bin/node_modules/npm/bin/node-gyp-bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/aria2/bin
> 10 verbose lifecycle ieaseMusic@1.0.0~build-all: CWD: /Users/lawrencelaw/ieaseMusic
> 11 silly lifecycle ieaseMusic@1.0.0~build-all: Args: [ '-c', 'npm run build-main && npm run build-renderer' ]
> 12 silly lifecycle ieaseMusic@1.0.0~build-all: Returned: code: 2  signal: null
> 13 info lifecycle ieaseMusic@1.0.0~build-all: Failed to exec build-all script
> 14 verbose stack Error: ieaseMusic@1.0.0 build-all: `npm run build-main && npm run build-renderer`
> 14 verbose stack Exit status 2
> 14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
> 14 verbose stack     at EventEmitter.emit (events.js:315:20)
> 14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
> 14 verbose stack     at ChildProcess.emit (events.js:315:20)
> 14 verbose stack     at maybeClose (internal/child_process.js:1051:16)
> 14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
> 15 verbose pkgid ieaseMusic@1.0.0
> 16 verbose cwd /Users/lawrencelaw/ieaseMusic
> 17 verbose Darwin 17.7.0
> 18 verbose argv "/usr/local/Cellar/node/14.3.0/bin/node" "/usr/local/bin/npm" "run" "build-all"
> 19 verbose node v14.3.0
> 20 verbose npm  v6.14.4
> 21 error code ELIFECYCLE
> 22 error errno 2
> 23 error ieaseMusic@1.0.0 build-all: `npm run build-main && npm run build-renderer`
> 23 error Exit status 2
> 24 error Failed at the ieaseMusic@1.0.0 build-all script.
> 24 error This is probably not a problem with npm. There is likely additional logging output above.
> 25 verbose exit [ 2, true ]

**Comment by daihy8759** [comment]
yarn dev能启动起来么

**Comment by kjlawrencelaw** [comment]
> yarn dev能启动起来么

只能得到以下的错误提示

> (electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
> GVA error: Not detecting IGPU in IORegistry!
> GVA error: Not detecting valid offline codec!
> GVA info: Successfully connected to the Intel plugin, offline Gen6 
> ✖ ｢wdm｣: 
> ERROR in ./src/renderer/views/Search/index.tsx
> Module Error (from ./node_modules/eslint-loader/index.js):
> 
> /Users/lawrencelaw/ieaseMusic/src/renderer/views/Search/index.tsx
>   70:25  error  Unexpected empty arrow function  @typescript-eslint/no-empty-function
> 
> ✖ 1 problem (1 error, 0 warnings)
> 
>  @ ./src/renderer/routes/index.tsx 29:32-57
>  @ ./src/renderer/App.tsx
>  @ ./src/renderer/index.tsx
>  @ multi react-hot-loader/patch ./src/renderer/index.tsx

![Screen Shot 2020-06-04 at 09 20 33](https://user-images.githubusercontent.com/13857562/83704439-aa196780-a644-11ea-8c7c-1a70e73758cd.png)
